"""
Creates expression annotation and expression matrix that can be used by
other tests
"""
import dill as pickle
from pathlib import Path

import networkx as nx
import pandas as pd
import logging
import GEOparse
import pytest

from Expressions.ExpressionMatrix import ExpressionMatrix, ExpressionMatrixTimeSeries
from DynamicModels.ModuleRegulatoryNetwork import ModuleRegulatoryNetwork, \
    EdgeRelation
from DynamicModels.OdeModel import OdeModel
from helpers import get_info_from_gse65046

pd.options.display.width = 0
# GEOparse.logger.set_verbosity('INFO')
# logging.basicConfig(level=logging.INFO)

@pytest.fixture
def static_expression_two_temps_arabidopsis() -> ExpressionMatrix:
    """Use prepickled expression matrix because that is just way faster"""
    with open('../data/static_datasets/GSE15689_family_ExpressionMatrix.pickle',
              'rb') as f:
        expr_mat = pickle.load(f)
    return expr_mat

@pytest.fixture
def my_time_series_expressions() -> ExpressionMatrixTimeSeries:
    """Use this to skip the full creation of the object, and simply extract it
    from the pickle file that was created by the test above this one."""
    # # Preparatory work
    # expr_mat_time = ExpressionMatrixTimeSeries.from_geo_file(
    #     Path('../data/raw_data/expression_datasets/gse65046/GSE65046_family.soft'),
    #     log2_transform=True,
    #     annotate_from_gpl=True
    # )
    # expr_mat_time.df = expr_mat_time.df.iloc[:50,:]
    # with open('test_data/GSE65046_family_test50_genes.pkl', 'wb') as f:
    #     pickle.dump(expr_mat_time, f)
    # print()
    with open('test_data/GSE65046_family_test50_genes.pkl', 'rb') as f:
        expr_mat_time = pickle.load(f)
    expr_mat_time.column_parser = get_info_from_gse65046
    expr_mat_time.summary_method = 'mean'
    return expr_mat_time


@pytest.fixture
def my_tf2_input(my_time_series_expressions):
    """
    Create a file that can be used on
    http://bioinformatics.psb.ugent.be/webtools/TF2Network/
    to get putative regulators per cluster
    """
    total_genes = 2000
    my_time_series_expressions.keep_only_shoot()
    my_time_series_expressions.merge_biological_samples()
    my_time_series_expressions.keep_n_most_deviating_genes(total_genes, 'mad')
    my_time_series_expressions.do_hierachical_clustering(4, do_plotting=False)
    # my_time_series_expressions.plot_clusters_over_time(plot_units=False)
    # my_time_series_expressions.plot_clusters_over_time(plot_units=True)
    my_time_series_expressions.write_tf2_input_file(
        Path(f'../data/time_series_datasets/tf2network_approach/{total_genes}_highest_mad_log2/01_tf2network_input_{total_genes}_highest_mad_genes.txt'))
    my_time_series_expressions.save_tf_produced_by_module_file(
        Path(
            f'../data/time_series_datasets/tf2network_approach/{total_genes}_highest_mad_log2/02_gene_to_module.csv'),
        Path('../data/resources/Ath_TF_list.txt')
    )
    # my_time_series_expressions.plot_clusters_over_time()
    return my_time_series_expressions

@pytest.fixture
def my_tf2_network(my_tf2_input: ExpressionMatrixTimeSeries) -> ModuleRegulatoryNetwork:
    """
    Point this path to the output of TF2network (generated by ticking
    the direct export button on the main page)
    """
    total_genes = 2000
    my_grn = ModuleRegulatoryNetwork.from_tf2_tsv(
        Path(
            f'../data/time_series_datasets/tf2network_approach/{total_genes}_highest_mad_log2/03_tf2network_output.tsv'))
    my_grn.add_tf_module_mappings(
        Path(
            f'../data/time_series_datasets/tf2network_approach/{total_genes}_highest_mad_log2/02_gene_to_module.csv'))
    my_grn.clean_up_network()
    my_grn.plot_network(with_labels=True)
    my_grn.check_if_tfs_created_by_module(my_tf2_input, do_plotting=True, remove_low_corr=True)
    my_grn.set_up_or_downregulation(my_tf2_input, do_plotting=True)
    # my_tf2_input.get_correlation(2, 'AT1G18330')
    my_grn.plot_network(nx.draw_kamada_kawai, with_labels=False)
    module_module = my_grn.get_module_module_network()
    module_module.plot_network(with_labels=True)
    return module_module

@pytest.fixture
def my_module_module_network(my_grn: ModuleRegulatoryNetwork) -> ModuleRegulatoryNetwork:
    my_grn.clean_up_network()
    # my_grn.plot_network(with_labels=False)
    my_module_network = my_grn.get_module_module_network()
    # my_module_network.plot_network(with_labels=False)
    return my_module_network

@pytest.fixture
def my_ode(my_module_module_network: ModuleRegulatoryNetwork) -> OdeModel:
    return my_module_module_network.convert_to_ode()

@pytest.fixture
def my_seed_expressions() -> ExpressionMatrix:
    seed_expression_path = Path('../data/static_datasets/seed_normalized_counts.csv')
    return ExpressionMatrix.from_csv(seed_expression_path)
