"""
Creates expression annotation and expression matrix that can be used by
other tests
"""
import pickle
from pathlib import Path

import pandas as pd
import logging
import GEOparse
import pytest

from Expressions.ExpressionArrayAnnotation import ExpressionArrayAnnotation
from Expressions.ExpressionMatrix import ExpressionMatrix, ExpressionMatrixTimeSeries
from DynamicModels.ModuleRegulatoryNetwork import ModuleRegulatoryNetwork
from DynamicModels.OdeModel import OdeModel

pd.options.display.width = 0
# GEOparse.logger.set_verbosity('INFO')
# logging.basicConfig(level=logging.INFO)


@pytest.fixture
def my_expression_annotation():
    my_path = Path('../data/resources/affy_ATH1_array_elements-2010-12-20.txt')
    return ExpressionArrayAnnotation(my_path)


@pytest.fixture
def static_expression_two_temps_arabidopsis_from_file(
        my_expression_annotation: ExpressionArrayAnnotation):
    # TODO make this an explicit test?
    my_expression = Path('../data/static_datasets/GSE15689_family.soft')
    expr_mat = ExpressionMatrix.from_geo_file(my_expression,
                                              my_expression_annotation)
    return expr_mat


@pytest.fixture
def static_expression_two_temps_arabidopsis() -> ExpressionMatrix:
    """Use prepickled expression matrix because that is just way faster"""
    with open('../data/static_datasets/GSE15689_family_ExpressionMatrix.pickle',
              'rb') as f:
        expr_mat = pickle.load(f)
    return expr_mat


@pytest.fixture
def my_time_series_expressions_from_file(
        my_expression_annotation: ExpressionArrayAnnotation) -> ExpressionMatrixTimeSeries:
    time_series_expressions = Path(
        '../data/time_series_datasets/GSE5628_family.soft')
    expr_mat_time = ExpressionMatrixTimeSeries.from_geo_file(
        time_series_expressions, my_expression_annotation, log2_transform=True)
    with open('../data/time_series_datasets/GSE5628_family_ExpressionMatrixTime.pickle', 'wb') as f:
        pickle.dump(expr_mat_time, f)
    return expr_mat_time


@pytest.fixture
def my_time_series_expressions(my_expression_annotation: ExpressionArrayAnnotation) -> ExpressionMatrixTimeSeries:
    with open('../data/time_series_datasets/GSE5628_family_ExpressionMatrixTime.pickle', 'rb') as f:
        expr_mat_time = pickle.load(f)
    return expr_mat_time

# @pytest.fixture
# def my_grn() -> ModuleRegulatoryNetwork:
#     path_to_network_edges = Path(
#         '../data/time_series_datasets/aracne_network_edges.csv')
#     path_to_orignal_cluster = Path(
#         '../data/time_series_datasets/my_clustering_edgelist.csv')
#     my_graph = ModuleRegulatoryNetwork.from_lpan_edge_csv(path_to_network_edges,
#                                                           top_rank=25)
#     my_graph.add_tf_module_mappings(path_to_orignal_cluster)
#     return my_graph

@pytest.fixture
def my_grn() -> ModuleRegulatoryNetwork:
    path_to_network_edges = Path(
        '../Explanatory_tutorial/aracne_network_edges.csv')
    path_to_orignal_cluster = Path(
        '../Explanatory_tutorial/my_clustering_edgelist.csv')
    my_graph = ModuleRegulatoryNetwork.from_lpan_edge_csv(path_to_network_edges,
                                                          top_rank=25)
    my_graph.add_tf_module_mappings(path_to_orignal_cluster)
    return my_graph

@pytest.fixture
def my_tf2_input(my_time_series_expressions):
    """
    Create a file that can be used on
    http://bioinformatics.psb.ugent.be/webtools/TF2Network/
    to get putative regulators per cluster
    """
    my_time_series_expressions.keep_only_shoot()
    my_time_series_expressions.merge_biological_samples()
    my_time_series_expressions.keep_only_de_genes(std_cutoff=1)
    my_time_series_expressions.do_hierachical_clustering(4)
    my_time_series_expressions.write_tf2_input_file(Path('../data/time_series_datasets/tf2network_approach/genes_per_cluster_cutoff1.txt'))
    my_time_series_expressions.plot_clusters_over_time()

@pytest.fixture
def my_tf2_ode():
    """
    Point this path to the output of TF2network (generated by ticking
    the direct export button on the main page)
    """
    my_grn = ModuleRegulatoryNetwork.from_tf2_tsv(
        Path('../data/time_series_datasets/tf2network_approach/tf2network_output_stdev_cutoff_1.tsv'))
    my_grn.add_tf_module_mappings(
        Path('../data/time_series_datasets/my_clustering_edgelist.csv'))
    my_grn.clean_up_network()
    my_grn.plot_network()
    module_module = my_grn.get_module_module_network()
    # module_module.plot_network()
    return module_module.convert_to_ode()

@pytest.fixture
def my_module_module_network(my_grn: ModuleRegulatoryNetwork) -> ModuleRegulatoryNetwork:
    my_grn.clean_up_network()
    # my_grn.plot_network(with_labels=False)
    my_module_network = my_grn.get_module_module_network()
    # my_module_network.plot_network(with_labels=False)
    return my_module_network

@pytest.fixture
def my_ode(my_module_module_network: ModuleRegulatoryNetwork) -> OdeModel:
    return my_module_module_network.convert_to_ode()

@pytest.fixture
def my_seed_expressions() -> ExpressionMatrix:
    seed_expression_path = Path('../data/static_datasets/seed_normalized_counts.csv')
    return ExpressionMatrix.from_csv(seed_expression_path)
