IDS, = glob_wildcards("data/resources/cig_data/split_per_module/{id}.txt")

rule target:
    input:
        expand("data/resources/cig_data/module_go_enrichment_all_genes_background/{id}.tsv", id=IDS)

rule go_annotate:
    input:
        "data/resources/cig_data/split_per_module/{id}.txt",
        "data/resources/go_annotations/ATH_GO_GOSLIM_genes_only.txt",
        "data/resources/go_annotations/ATH_GO_GOSLIM_one_gene_per_line.txt",
    params:
        obo="data/resources/go_annotations/go-basic.obo"
    output:
        "data/resources/cig_data/module_go_enrichment_all_genes_background/{id}.tsv"
    log:
        "data/resources/cig_data/module_go_enrichment_log_all_genes_background/{id}.log"
    shell:
        "find_enrichment.py {input} --obo {params.obo} --outfile {output} > {log}"